version: '3.9'
volumes:
    logs-cache:
    db-data:
services:
    nginx:
        container_name: nginx
        image: nginx:1.21.6-alpine
        restart: always
        volumes:
            - ./public:/var/www/public
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8080:80"
        depends_on:
            - app-service
    worker-service:
        restart: always
        container_name: worker
        build:
            context: .
            target: worker
        depends_on:
            - database
    app-service:
        container_name: app
        restart: always
        build:
            context: .
            target: app
            args:
                - APP_ENV=dev
#        volumes:
#            - logs-cache:/var/www/var
        environment:
            DATABASE_URL: "postgresql://db_user:db_password@database:5432/db_name?serverVersion=14&charset=utf8"
        depends_on:
            - database
    database:
        container_name: database
        image: postgres:14.1-alpine
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: db_user
            POSTGRES_PASSWORD: db_password
            POSTGRES_DB: db_name
