name: Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  coverage: xdebug
            - uses: ramsey/composer-install@v2
            - name: 🧪 Tests
              run: docker-compose run app ./vendor/bin/phpunit  --coverage-clover clover.xml
            - uses: codecov/codecov-action@v2
              with:
                  files: ./clover.xml
